config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:index, :show] do
    resources :posts do
      resources :comments, only: [:create, :destroy]
      resources :likes, only: [:create, :destroy]
    end
  end

  namespace :api do
    namespace :v1 do
      post '/login', to: 'authentication#login'

      resources :users, only: [:show] do
        resources :posts, only: [:index, :show] do
          resources :comments, only: [:create, :index]
        end
      end
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "users#index"
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: :author_id
  belongs_to :post

  after_save :update_comments_counter
  after_destroy :update_comments_counter

  def update_comments_counter
    post.update(comments_counter: post.comments.count)
  end

  private :update_comments_counter
end

app/controllers/api/v1/comments_controller.rb
class Api::V1::CommentsController < ApplicationController
  include JsonWebToken
  skip_before_action :verify_authenticity_token
  before_action :authenticate_request

  def index
    @comments = Post.find(params[:post_id]).comments
    respond_to do |format|
      format.json { render json: @comments }
      format.html { render json: @comments }
    end
  end

  def create
    @post = Post.find(params[:post_id])
    @comment = Comment.new(comment_params)
    @comment.author = @current_user
    @comment.post = @post
    if @comment.save
      render json: @comment, status: :created
    else
      render json: { errors: @comment.errors.full_messages }, status: :unprocessable_entity
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @user = current_user
    @post = Post.find(params[:id])
    @comment = Comment.new
  end

  def create
    @user = current_user
    @post = Post.find(params[:post_id])
    @comment = Comment.new(comment_params)
    @comment.author = @user
    @comment.post = @post
    if @comment.save
      flash[:success] = 'Comment saved successfully'
      redirect_to user_posts_path(@post.author)
    else
      flash.now[:error] = 'Error: Comment could not be saved'
      render :new, status: 422
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy

    redirect_to user_path(params[:user_id], params[:post_id]), status: :see_other
  end

  private

  def comment_params
    params.require(:comment).permit(:text, :author, :post)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<li class="comment">
  <%= link_to comment.author.name, user_path(comment.author_id) %>: <%= comment.text %>
  <% if can? :manage, comment %>
    <ul class=comment__tools>
      <li><%= link_to "Delete comment", user_post_comment_path(comment.author, comment.post, comment), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %></li>
    </ul>
  <% end %>
</li>

app/views/comments/_form.html.erb
<%= form_with model: @comment, url: user_post_comments_url(@post.author, @post), scope: :comment, method: :post do |f| %>
  <h2>Add a new comment</h2>
  <div>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </div>
  <div>
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/new.html.erb
<%= render @user %>
<%= render @post %>
<%= render 'form' %>