config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:index, :show] do
    resources :posts do
      resources :comments, only: [:create, :destroy]
      resources :likes, only: [:create, :destroy]
    end
  end

  namespace :api do
    namespace :v1 do
      post '/login', to: 'authentication#login'

      resources :users, only: [:show] do
        resources :posts, only: [:index, :show] do
          resources :comments, only: [:create, :index]
        end
      end
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "users#index"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :posts, foreign_key: 'author_id', dependent: :destroy
  has_many :likes, foreign_key: 'author_id', dependent: :destroy
  has_many :comments, foreign_key: 'author_id', dependent: :destroy

  validates :posts_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :name, presence: true

  def last_three_posts
    Post.includes(%i[author comments]).where(author: self).order(created_at: :desc).first(3)
  end

  def admin?
    role == 'admin'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_user.html.erb
<ul class="users">
  <li class="user">
    <%= link_to user_path(user.id), id: "userlink-#{user.id}" do %>
      <div class="user__photo">
        <img src=<%= user.photo %> alt=<%= user.name %>>
      </div>
      <div class="user__container">
        <div class="user__name"><%= user.name %></div>
        <div class="user__posts_counter">Number of Posts: <%= user.posts_counter %></div>
      </div>
    <% end %>
  </li>
</ul>

app/views/users/index.html.erb
<h1>Users</h1>
<p>Here is the list of users retrieved from the database</p>
<% if @users.empty? %>
  <h2>No users on database</h2>
<% else %>
  <%= render @users %>
<% end %>

app/views/users/show.html.erb
<h1>User <%= @user.name %></h1>
<p>Here are the details of a user given its id</p>
<%= link_to '< Back to users', users_path %>
<%= render @user %>
<div class="user__new_post">
  <h3><%= link_to 'Create a new post', new_user_post_path(@user.id) %></h3>
</div>

<div class="user__bio">
  <h2>Bio</h2>
  <p><%= @user.bio %></p>
</div>

<% if @user.posts.empty? %>
  <h2>No posts created</h2>
<% else %>
  <% @user.last_three_posts.each do |post| %>
    <%= render post %>
  <% end %>
  <%= link_to 'See all posts', user_posts_path(@user.id) if @user.posts_counter > 3 %>
<% end %>