config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:index, :show] do
    resources :posts do
      resources :comments, only: [:create, :destroy]
      resources :likes, only: [:create, :destroy]
    end
  end

  namespace :api do
    namespace :v1 do
      post '/login', to: 'authentication#login'

      resources :users, only: [:show] do
        resources :posts, only: [:index, :show] do
          resources :comments, only: [:create, :index]
        end
      end
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "users#index"
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: :author_id
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy

  after_save :update_posts_counter
  after_destroy :update_posts_counter

  validates :title, presence: true
  validates :title, length: { maximum: 250 }
  validates :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :comments_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def update_posts_counter
    author.update(posts_counter: author.posts.count)
  end

  def five_most_recent_comments
    comments.includes([:author]).order(updated_at: :desc).first(5)
  end

  private :update_posts_counter
end

app/controllers/api/v1/posts_controller.rb
class Api::V1::PostsController < ApplicationController
  def index
    @posts = User.find(params[:user_id]).posts

    respond_to format do
      format.json { render json: @posts }
      format.html { render json: @posts }
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource

  def index
    @user = User.find(params[:user_id])
    @posts = @user.posts.includes(%i[author comments]).order(created_at: :desc)
  end

  def show
    @user = current_user
    @post = Post.find(params[:id])
    @comments = @post.comments.includes([:author])
  end

  def new
    @user = current_user
    @post = Post.new
  end

  def create
    @user = current_user
    @post = @user.posts.create(post_params)
    if @post.save
      flash[:success] = 'Post saved successfully'
      redirect_to user_posts_path(@post.author)
    else
      flash.now[:error] = 'Error: Post could not be saved'
      render :new, status: 422
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    redirect_to user_path(params[:user_id]), status: :see_other
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with model: @post, url: user_posts_path, method: :post, scope: :post do |f| %>
  <div>
    <%= f.label :title %><br/>
    <%= f.text_field :title %>
  </div>
  
  <div>
    <%= f.label :text %><br/>
    <%= f.text_area :text %>
  </div>

  <div><%= f.submit %></div>
<% end %>

app/views/posts/_post.html.erb
<ul class="posts">
  <li class="post">
    <%= link_to user_post_path(post.author_id, post.id), id: "postlink-#{post.id}" do %>
      <div class="post__container">
        <div class="post__title"><%= post.title %></div>
        <div class="post__text"><%= post.text %></div>
        <div class="post__indicators">
          <div class="post__comments_counter">Comments: <%= post.comments_counter %></div>
          <div class="post__likes_counter">Likes: <%= post.likes_counter %></div>
        </div>
      </div>
    <% end %>
    <% if can? :manage, post %>
      <ul class=post__tools>
        <li><%= link_to "Delete Post", user_post_path(post.author, post), data: {
                      turbo_method: :delete,
                      turbo_confirm: "Are you sure?"
                    } %></li>
      </ul>
    <% end %>
    <ul class="post__comments">
    <% if post.comments.empty? %>
      <li>No comments</li>
    <% else %>
      <% post.five_most_recent_comments.each do |comment| %>
        <%= render comment %>
      <% end %>
    <% end %>
    </ul>
  </li>
</ul>

app/views/posts/index.html.erb
<h1>Posts</h1>
<p>Here is a list of posts of a given user</p>
<%= render @user %>
<div class="user__new_post">
  <h3><%= link_to 'Create a new post', new_user_post_path(@user.id) %></h3>
</div>
<% if @posts.empty? %>
  <h2>No posts created</h2>
<% else %>
  <%= render @posts %>
<% end %>
<button type="button">Pagination</button>

app/views/posts/new.html.erb
<h2>Create a new post</h2>
<%= render @user %>
<%= render 'form' %>

app/views/posts/show.html.erb
<div class="detailed_post">
  <div class="post__header">
    <div class="post__title"><%= @post.title %> by <%= link_to @post.author.name, user_path(@post.author_id) %></div>
    <div class="post__indicators">
      <div class="post__comments_counter">Comments: <%= @post.comments_counter %></div>
      <div class="post__likes_counter">Likes: <%= @post.likes_counter %></div>
    </div>
  </div>
  <div class="post__full_text"><%= @post.text %></div>
  <%= render 'comments/form' %>
  <%= form_with url: user_post_likes_url(@post.author, @post), method: 'post' do |f| %>
    <div>
      <%= f.submit 'Like' %>
    </div>
  <% end %>
  <ul class="post__comments">
    <%= render @comments %>
  </ul>
</div>